[package]
name = "RustCliAnalysis"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
clap = "3.0"
statrs = "0.15"
rand = "0.8"

